### ISSUE TITLE
你功能都做完了，我搞个锤子？

### ISSUE THREAD

**Issue by FlyingMcDonald** [Ihexon/fileyze#1]
你让我做什么？！！！

**Comment by ihexon** [comment]
- 如果监听的目录没有权限，则会抛出异常

- Linux上某些特殊的文件系统不能监听，如socks设备，fd设备等，/dev/block设备等，需要增加判断跳过这些特殊文件设备

- 一个目录有较多子目录时，建议增加多线程监听

- 记录日志LOG存储
